### ISSUE TITLE
IA64 in README.md

### ISSUE THREAD

**Issue by kubo** [mikra01/nimodpi#1]
In README.md:
> I tested it only for the IA64 architecture and only tested against nim-compiler version 1.0.2.

Did you confuse [x86-64][] with [IA-64][]?

[IA-64]: https://en.wikipedia.org/wiki/IA-64
[x86-64]: https://en.wikipedia.org/wiki/X86-64

**Comment by mikra01** [comment]
no - it's an old hp-machine I sometimes play with - but main platform will be AMD64 in the future..

**Comment by kubo** [comment]
Okay. I thought that you had tested nimodpi on Windows x64 because you wrote "I tested it only for the windows 10 OS" about Oracle XE installation in README.md.

**Comment by mikra01** [comment]
yeah I know the readme is a little bit inconsistent at the moment; thanks for pointing that out. Basically the wrapper should run on every platform where the instantclient, Nim and a C-compiler is available. At the moment I moved to windows10, 64bit gcc and a local XE installation (I additionally plan to test that setup with MSVC).
